added github workflows

diff --git a/.github/workflows/github-actions.yaml b/.github/workflows/github-actions.yaml
--- a/.github/workflows/github-actions.yaml
+++ b/.github/workflows/github-actions.yaml
@@ -99,12 +99,12 @@ jobs:
       #         body
       #       });
 
-      # - name: Fail if Terraform Plan failed (syntax or auth issue)
-      #   if: steps.plan.outputs.exitcode == '1'
-      #   run: |
-      #     echo "❌ Terraform plan failed with exit code 1"
-      #     exit 1
+      - name: Fail if Terraform Plan failed (syntax or auth issue)
+        if: steps.plan.outputs.exitcode == '1'
+        run: |
+          echo "❌ Terraform plan failed with exit code 1"
+          exit 1
 
-      # - name: Terraform Apply
-      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-      #   run: terraform apply -auto-approve
+      - name: Terraform Apply
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+        run: terraform apply -auto-approve
